# Generated by Django 3.1.7 on 2021-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210308_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='profile',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
